name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  py_test:
    runs-on: ubuntu-latest
    name: Test - Python
    defaults:
      run:
        working-directory: ./react-app/mock-buddy/app
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install portaudio19-dev
          pip install pylint pytest pytest-cov
          pip install -r requirements.txt
      - name: Analyze
        run: |
          python -m pylint --extension-pkg-whitelist=cv2
          pylint $(git ls-files '*.py')
      # - name: Test
      #   run: |
      #     python -m pytest --cov=./ --cov-report=xml
      # - name: Upload coverage report to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     env_vars: OS,PYTHON
      #     fail_ci_if_error: false
      #     flags: unittests
      #     verbose: true